### ISSUE TITLE
Trying to unmarshall the test run plan XML file: /home/kali/...../TestRunPlan.xml

### ISSUE THREAD

**Issue by Trickevtarike** [BSI-Bund/TaSK#30]
is there any explanation for this issue?

2024-09-23T12:01:47.195 DEBUG MSG: RunPlan Parser: Trying to unmarshall the test run plan XML file: /home/kali/Downloads/TaSK-1.0.1/report/2024-09-23T120145_TestReport/TestRunPlan.xml
2024-09-23T12:04:01.115 ERROR MSG: TaSK: Error occurred while trying to parse the test run plan file. EXC:java.lang.RuntimeException: Unable to register RMI ClientExecutor.
        at com.achelos.task.dutmotivator.GenericClientExecutableDUTMotivator.<init>(GenericClientExecutableDUTMotivator.java:25)
        at com.achelos.task.configuration.TestRunPlanConfiguration.setDUTCommandGenerator(TestRunPlanConfiguration.java:123)
        at com.achelos.task.configuration.TestRunPlanConfiguration.parseRunPlanConfiguration(TestRunPlanConfiguration.java:79)
        at com.achelos.task.abstractinterface.TaskTestTool.executeTaskTestToolRun(TaskTestTool.java:329)
        at com.achelos.task.abstractinterface.TaskTestTool.executeTaskTestTool(TaskTestTool.java:175)
        at com.achelos.task.abstractinterface.TaskTestTool.executeTaskTesttool(TaskTestTool.java:215)
        at com.achelos.task.abstractinterface.TaskTestTool.executeTaskTestTool(TaskTestTool.java:200)
        at com.achelos.task.commandlineinterface.CommandLineInterface.executeMicsMode(CommandLineInterface.java:391)
        at com.achelos.task.commandlineinterface.CommandLineInterface.main(CommandLineInterface.java:178)

Thanks

**Comment by dc3963192** [comment]
Hello, could you please provide us more information about your setup. 
•	How does your TestRunPlan.xml file look like?
•	Which operating system are you working on?
•	How did you setup the RMI Client Executor?
