### ISSUE TITLE
Build fails behind Proxy Server

### ISSUE THREAD

**Issue by jblu42** [BSI-Bund/TaSK#7]
If behind a proxy server (which is often the case in a corporate environment) installation fails, because it cannot connect to test-check.de (or did I do something wrong?)

2023-01-13T10:14:25.019 INFO MSG: MICS Verifier: Successfully parsed the MICS file: ../data/input/ExampleMICS_Server.xml
2023-01-13T10:14:25.019 INFO MSG: MICS Verifier: Verifying the MICS file..
2023-01-13T10:14:25.019 DEBUG MSG: MICS Verifier: Checking if "CHECK_CERTS" profile is set in the MICS file.
2023-01-13T10:14:25.019 DEBUG MSG: MICS Verifier: Found "CHECK_CERTS" profile in the MICS file.
2023-01-13T10:14:25.019 DEBUG MSG: MICS Verifier: Verifying the existence of provided certificate files.
2023-01-13T10:14:25.019 DEBUG MSG: MICS Verifier: Existence of provided certificate files successfully verified.
2023-01-13T10:14:25.019 DEBUG MSG: MICS Verifier: Searching for applicable application specification and application mapping.
2023-01-13T10:14:25.019 DEBUG MSG: MICS Verifier: Found applicable application specification.
2023-01-13T10:14:25.019 DEBUG MSG: MICS Verifier: Found applicable application mapping.
2023-01-13T10:14:25.019 INFO MSG: MICS Verifier: Verifying the Device Under Test.
2023-01-13T10:14:25.021 DEBUG MSG: MICS Verifier: Running DUT verifier on the provided MICS file.
2023-01-13T10:14:25.021 DEBUG MSG: MICS Verifier: DUT is of type: TR-03116-4-SERVER
2023-01-13T10:14:25.021 DEBUG MSG: MICS Verifier: Verifying server URL: tls-check.de.
java.lang.RuntimeException: MICS Verifier:  Error occurred while trying to verify the provided MICS file.
        at com.achelos.task.micsverifier.MICSVerifier.verifyMICS(MICSVerifier.java:182)
        at com.achelos.task.micsverifier.MICSVerifier.verifyMICS(MICSVerifier.java:96)
        at micsverifier.TestMICSVerifier.testMICSVerifier(TestMICSVerifier.java:40)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
        at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
        at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
2023-01-13T10:14:25.023 ERROR MSG: MICS Verifier: DUT has a server type, but the provided server URL could not be verified. EXC:java.net.UnknownHostException: tls-check.de: Temporary failure in name resolution

**Comment by nb-2020** [comment]
Hi, thanks for reporting the issue. We agree with your analysis and will provide a fix in one of the next releases.

**Comment by rk8129406** [comment]
Issue has been fixed with the 1.0.1 release.
